### ISSUE TITLE
When selecting and dragging, the layers become visible.

### ISSUE THREAD

**Issue by hickscorp** [winhowes/parallax-container#4]
## Steps to reproduce:

- Open the demo,
- Start selecting text from left to right, and continue dragging to the right.

## Expected result:

The page shouldn't scroll right.

## Actual Result:

The page scrolls right, and therefore all the layers become ugly and visible.

**Comment by winhowes** [comment]
What browsers are you experiencing this on? I tested Chrome and Firefox and could not reproduce the issue :/

**Comment by winhowes** [comment]
Ah, okay this seems to be the case when the browser is not full screen, and thus you can drag off the end of the screen. Looking into it

**Comment by winhowes** [comment]
This seems to be an issue in webkit-based browsers. There is already `overflow-x: hidden;` on the parallax-container. Oddly, changing that to just `overflow: hidden;` resolves the issue, but also kills vertical scrolling. I'm going to close this as `wontfix` as the solution requires some incredibly intrusive js

**Comment by winhowes** [comment]
I've pushed a patch which should resolve this issue. Let me know if you run into any problems!
